导库

In [1]:
import tensorflow as tf

创建数据(Tensor)

In [2]:
# 不同硬件上创建数据
with tf.device("cpu"):
    a = tf.constant([1])
with tf.device("GPU"):
    b = tf.constant([1])
print(a.device)
print(b.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:GPU:0


In [3]:
print(tf.constant(1)) # 标量 scalar
print(tf.constant([1])) # 向量 vector
print(tf.constant([[1],[1]])) # 矩阵 matrix

print(tf.constant(1)) # 整型 int
print(tf.constant(1.)) # 单精度浮点型 float
print(tf.constant(1.,dtype=tf.double)) # 双精度浮点型 double
print(tf.constant([True,False])) # 布尔型 bool
print(tf.constant('hello word')) # 字符串 string


tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor(
[[1]
 [1]], shape=(2, 1), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor([ True False], shape=(2,), dtype=bool)
tf.Tensor(b'hello word', shape=(), dtype=string)


Tensor的属性和方法

In [4]:
a.gpu() # 转换到gpu
b.cpu() # 转换到cpu

print(b.numpy()) # 转换成numpy

print(b.ndim) # 维度
print(b.shape) # 形状
print(b.dtype) # 类型
print(b.device) # 设备

Instructions for updating:
Use tf.identity instead.
Instructions for updating:
Use tf.identity instead.
[1]
1
(1,)
<dtype: 'int32'>
/job:localhost/replica:0/task:0/device:GPU:0


In [5]:
# 判断是否tensor
print(isinstance(a,tf.Tensor))
print(tf.is_tensor(a))


# 判断数据类型
a.dtype == tf.int32

True
True


True